user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzEwOA==

session:
  key: gAAAAABhLCkOdqAT5MNv8ekUG5IAw8a1JylkF12i_tWtgwWPPI25tpmtBzWlNKY46XvX2i9VVwXOHMZ4EX88SVj9sNqwy1lP1YhQOSOjTnxNOJCvNRz65M2T37hmBg15-yZN49ADpxq1PccJqlvkXbfLaMVONS_LNpS2eMB5x0Vu40b846wp6v9lqu51EBO1XQnApMSSedDIK7Sqwb9NBcCHxfm5d0EqzAUKw1bu8--RiBlTmF7uOnrlwzsoOB4YaB9hmGQyMxDStZN2mZsMuWjn7grlxVBTucay8ZmdhaM4o1D-LHBv00-4jck40VHzd1uGQWVswkrqsYWMvasnHa9bwkVz3WuEywL3FLbcF-LATrx4U5tTxsOEZE2-X-cDbM-nf2eaCwO3Ziu1dNd-DMVEGP2F-1AfS6rVeEytm6mA8pLTjk1Emww=
admin:
  email: admin@admin.com
  password: admin
bot:
  token: group_token
  group_id: 1


